#!/bin/bash
set -e

echo "🐰 Writing hermes .env file from environment..."
mkdir -p /home/hermes/.hermes

# Write all relevant env vars to .env
cat > /home/hermes/.hermes/.env << ENVS
# Auto-generated by Docker entrypoint
HERMES_MODEL=${HERMES_MODEL:-openrouter:minimax/minimax-m2.7}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
DISCORD_ALLOWED_USERS=${DISCORD_ALLOWED_USERS:-588858125126336544}
DISCORD_REQUIRE_MENTION=${DISCORD_REQUIRE_MENTION:-false}
DISCORD_FREE_RESPONSE_CHANNELS=${DISCORD_FREE_RESPONSE_CHANNELS}
GATEWAY_ALLOW_ALL_USERS=${GATEWAY_ALLOW_ALL_USERS:-false}
HERMES_GATEWAY_PORT=${HERMES_GATEWAY_PORT:-18790}
HERMES_BACKGROUND_NOTIFICATIONS=${HERMES_BACKGROUND_NOTIFICATIONS:-result}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
MINIMAX_API_KEY=${MINIMAX_API_KEY:-}
ENVS

echo "✅ hermes .env written. Contents:"
cat /home/hermes/.hermes/.env

echo ""
echo "🚀 Starting hermes gateway..."
exec hermes gateway start
